### ISSUE TITLE
Exception in server tick loop - net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String; called in SMP

### ISSUE THREAD

**Issue by shirodave** [jaredlll08/ContentTweaker#1]
So hi,
I'm using MC Version 1.7.10 with Forge 10.13.4.1448 and your mod v. 1.0.3 unfortunately it crashes on Server startup. Please look at the crashlog on pastebin at: http://pastebin.com/2d6mSXLQ

**Comment by jaredlll08** [comment]
Fixed in 1.0.4 :)
