### ISSUE TITLE
[Bug or miss usage(?)] Fluid Texture NullPointerException

### ISSUE THREAD

**Issue by DerOliDE** [jaredlll08/ContentTweaker#2]
I've got a NullPointerException if i melt down (Tinkers Construct) items to a custom fluid. The Exception looks like it can render the fluid because he doesn't find the texture.

Crash-Report: https://gist.github.com/DerOli82/2f212d37afa31b4154e2
Fluid Script: https://github.com/combak/ShatteredWorld/blob/master/scripts/1-Fluids.zs
Textures Folder: https://github.com/combak/ShatteredWorld/tree/master/config/contenttweaker/icons/blocks

**Comment by jaredlll08** [comment]
There needs to be a texture, in the next version I'll add a default texture, but here are ones to use in the mean time, http://www.blamejared.com/content/textures.rar

**Comment by jaredlll08** [comment]
Also I noticed that you put contentTweaker scripts inside the normal scripts folder, this is incorrect and will cause other problems

**Comment by DerOliDE** [comment]
The wrong script folder was the main problem. Thank you for the quick help.

**Comment by DerOliDE** [comment]
By the way, a licence or modpack permissions would be nice. :) Doesn't find that here or on curse.com.

**Comment by jaredlll08** [comment]
I don't really care if people use my mod, like sending me a message would be nice, but I will very rarely say no
