### ISSUE TITLE
NPE on mods.content.Material.registerMaterial

### ISSUE THREAD

**Issue by dries007** [jaredlll08/ContentTweaker#3]
https://github.com/jaredlll08/ContentTweaker/blob/master/src/main/java/contentTweaker/content/ContentMaterials.java#L33-L46

You do a null check, but then forget to use `else if`
I suggest replacing 

``` java
if (nativeEnchantments == null)
    enchants = new EnchantmentWithLevel[0];
if (nativeEnchantments.length == 0)
    enchants = new EnchantmentWithLevel[0];
if (nativeEnchantments != null && nativeEnchantments.length > 0)  {
```

with 

``` java
if (nativeEnchantments == null || nativeEnchantments.length == 0)
    enchants = new EnchantmentWithLevel[0];
else {
```

**Comment by Claycorp** [comment]
You can't put enchantments or modifiers on by default at all. Three are commented out as they don't work. The last material does not work because it does not recognize the capacitor as a valid modifier item. 
Error: http://pastebin.com/8AZRqvb7
Formatted scripts: http://pastebin.com/9DLpThRm

**Comment by Claycorp** [comment]
I'm just going to assume that this mod isn't supported either as there was no response at all just like with {JSON}ables.
I'll just switch back to JSONables as it works as expected even though unsupported.

**Comment by jaredlll08** [comment]
Once again. I actually have a real life (currently writing final exams).
Things will get dealt with. Learn to be patient, go read a book or
something.

**Comment by Claycorp** [comment]
If I would have read a book while I was waiting for your snarky reply I could have read Mein Kampf ~8 times over if I read it for 5 hours a day in the time I already waited.

**Comment by jaredlll08** [comment]
Wow. Just wow. Great book selection, especially since I was raised Jewish and my great grandparents were in the Holocaust.

I'm sorry that you want to release a mod pack in a virtual game. I actually want to graduate school and do something with my life.

**Comment by jaredlll08** [comment]
Wow. Just wow. Great book selection, especially since I was raised Jewish
and my great grandparents were in the Holocaust.

I'm sorry that you want to release a mod pack in a virtual game. I actually
want to graduate school and do something with my life.

**Comment by Claycorp** [comment]
Yup and my father died. Totally relevant to the conversation at hand. +1

I'm sorry that you decided develop mods in a virtual world for said virtual game and actively still work on some of them. Must be a tough life. I actually like helping people and making things they enjoy to use/play with.

**Comment by TheCricket** [comment]
:tiger2:

**Comment by Fusty** [comment]
@Claycorp Submit a pull request of get out of here.

**Comment by dries007** [comment]
Please keep the drama on reddit or Twitter.  There is no need for this here.

**Comment by Lanse505** [comment]
@Claycorp 
Seriously just stop. 
Jared is trying his best to fix the issues that pop-up, no need to come off as a hostile little entitled kid.

**Comment by PapiDimmi** [comment]
@Claycorp Too edgy. 😎
