### ISSUE TITLE
On Using IItemDestroyedBlock. 

### ISSUE THREAD

**Issue by Kazerima** [jaredlll08/ContentTweaker#8]
there's no listed order for the parameters when using IItemDestroyedBlock. 

I'm trying to use the following code to make a test tool that creates a dirt block in the space of a stone block once it's been broken with the tool:

```
var item2 = VanillaFactory.createItem("block banana");

item.maxStackSize = 1;
item.maxDamage = 1;
item.itemDestroyedBlock = function(stack, world, blockState, pos, player) {
    if (blockState == <block:minecraft:stone>) {
	if (world.getBlockState(firePos).isReplaceable(world, pos)) {
	world.setBlockState(<block:minecraft:dirt>, pos);
        player.getHeldItem(hand).damage(1, player);
        return true;
	}
    }
    return true;
};
```

**Comment by Kazerima** [comment]
hello past self! I have good news and bad news.
The good news is that you made a lot of mistakes in your code using the wrong variable name.
The bad news is two years later you still are having trouble with exactly this same function for other reasons entirely.

**Comment by jaredlll08** [comment]
Also you're in the wrong repo
