### ISSUE TITLE
Not sure how to add texture.

### ISSUE THREAD

**Issue by Shovinus** [jaredlll08/ContentTweaker#9]
following the wiki I created an item:
```
#loader contenttweaker
import mods.contenttweaker.VanillaFactory;
import mods.contenttweaker.Item;
import mods.contenttweaker.IItemRightClick;
import mods.contenttweaker.Commands;

var zsItem = VanillaFactory.createItem("rail_cast");
zsItem.maxStackSize = 1;
zsItem.register();
```
which worked fine, but I am unsure how to add the texture for the item, I just want a flat item, not a block, I tried using zsItem.textureLocation but it came back stating that "No such member in mods.contenttweaker.Item: textureLocation"

please help, thank you.

**Comment by jaredlll08** [comment]
You got the wrong repo. Use the one from The Acronym Coders.

**Comment by Shovinus** [comment]
Oh, sorry, didn't realise 2 version

On 16 Sep 2018 01:10, Jared <notifications@github.com> wrote:

You got the wrong repo. Use the one from The Acronym Coders.
